language: go

go:
  - 1.10.x
  - 1.11.x

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/gordonklaus/ineffassign

script:
  - go vet
  - go test -v ./...
  - ineffassign .
