language: go

go:
  - 1.13.x

before_install:
  # Build tools
  - go get golang.org/x/lint/golint
  - go get github.com/gordonklaus/ineffassign

  - curl -sL https://github.com/dominikh/go-tools/releases/download/2019.2.3/staticcheck_linux_amd64.tar.gz | tar xz -C $GOPATH/bin --strip-components=1 staticcheck/staticcheck

  # Project dependencies
  - go get github.com/djherbis/times
  - go get github.com/mitchellh/go-homedir       
  - go get github.com/spf13/viper
  - go get github.com/gofrs/flock
  - go get gopkg.in/gomail.v2

script:
  - make test

  # run tests on a standard platform
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./... -race

  # Run static analysis
  - $GOPATH/bin/staticcheck

after_success:
  # Upload coverage results to codecov.io
  - bash <(curl -s https://codecov.io/bash)
